### PR TITLE
Use pre-commit to enforce linting

### PR DESCRIPTION
**Pull request by 12rambau**
This enforce linting operations from both local and distant side using pre-commit hooks. 

The pre-commit hook will run both `Black` and `Ruff` on the lib file and make adjustments if needed. You don't need to install them anymore and the pre-commit will also be run in the basic-ci script (in case a user forget to install it before pusing. 

In this PR I did: 
- add the pre-commit configuration 
- solved the linting issues (and/or exclude some files) 
- add the pre-commit to the CI 
- update the readme to tell contributors to use pre-commit 
- add some badges to the readme

### CODE REVIEW

**Comment by tcmetzger** [comment]
This is great, thank you! 
There are also some simple pytest tests in `tests/` - would you mind adding them to pre-commit, if they don't slow things too much? I can also look into that in a separate PR!

**Comment by 12rambau** [comment]
normally they are included as well, I added the compulsory minimal docstring to every function in test_options.py

**Comment by tcmetzger** [comment]
Do you know why the CI tests don't run in this PR, is this related to a change you made to the CI? 
Shouldn't there be a 

```
on: 
    pull_request
```

In there? My experience with GH actions is limited, so I might be totally wrong! 😊

**Comment by tcmetzger** [comment]
After https://github.com/tcmetzger/sphinx-favicon/pull/13, I believe we also need to update the python versions in .github/workflows/basic-ci.yml

**Comment by 12rambau** [comment]
done !

**Review by tcmetzger — APPROVED** [review]
This is great, thank you very much!

**Pull request merged**
