### PR TITLE
update documentation

### LINKED ISSUE #15: Add "breaking change" note to readme
https://github.com/tcmetzger/sphinx-favicon/pull/13 introduces a breaking change - the extension now needs to be imported with a different name in conf.py.
This needs to be communicated clearly in the readme and in the changelog (and other relevant places)

### LINKED ISSUE #21: use a favicon in the docs ?
I was thinking of using the doc as a small demo using the sphinx-contrib logo https://avatars.githubusercontent.com/u/31936682?s=200&v=4. 

I have a small favicon generator to get all the format at once

Bonus: I would like to change the theme for pydata-sphinx-theme and explain how to use `nox` in the contribution section

### PR DESCRIPTION
**Pull request by 12rambau**
- move the whole documentation in .rst 
- reduce the size of the readme and add disclaimer Fix #15 
- demonstrate nox usage 
- include modification from other PR (meta, extra parameters)
- use pydata-sphinx-theme
- use a disclaimer in the doc as well Fix #15 
- use custom favicons Fix #21 

I included some favicons in the list that will only be available after merging #24 and #25 but they remain commented at the moment

### CODE REVIEW

**Comment by tcmetzger** [comment]
@12rambau I tried building the docs from this branch (`nox -s build`), but I got `UndefinedError("'logo' is undefined")`. This seems related to https://github.com/pydata/pydata-sphinx-theme/issues/1094. 
I started with a completely new env (`rm -r .env`, `python3 -m venv .env`, `source .env/bin/activate`, `pip install -e .[dev]`, `nox -s docs`), running on Ubuntu WSL.

Do I understand correctly that this will be fixed with the next version of the theme? Do you know when that will be available?

**Comment by 12rambau** [comment]
@tcmetzger normally you don't need to create a new env manually, `nox` is doing it for you (that's the nice part). 

That being said you are right the latest version of pydata-sphinx-theme is not working with sphinx 6 as they changed one of the jinja variable (namely "logo" in favor of "logo_url"). We still have some work to do before releasing next version. What we suggested is pin the version of sphinx when building the doc, let me tune the configuration a bit to make it work.

**Comment by 12rambau** [comment]
work like a charm from readthedocs side: https://sphinx-favicon--27.org.readthedocs.build/en/27/

**Review by tcmetzger — APPROVED** [review]
Great work, thank you very much!
I made a few small adjustments and added the `lint` session to `noxfile.py`, as described in the docs!

**Pull request merged**
