### PR TITLE
change folder name

### LINKED ISSUE #11: could you change te name of the lib folder to sphinx_favicon ?
The folder containing the python package is currently `sphinx-favicon` which is not a legit python name. Most of the extention I know have usually a name with "-" and a folder with "_" like: "sphinx_copybutton", "sphinx_design", "jupyter_sphinx", "sphinx_design". 

I was working on the mypy issue to but it's not working as "sphinx-favicon" is not a legit python name.

### PR DESCRIPTION
**Pull request by 12rambau**
Fix #11 

Check carrefully that I didn't forgot something while updating the name. normally vscode does a good job at tracking this kind of modifications. 

- change the name of the folder 
- update the extention name in the readme (in the extention list) 
- update the name of the package in `setup.cfg`

### CODE REVIEW

**Comment by tcmetzger** [comment]
Thank you! Shouldn't we also update the Sphinx configs in the tests folder to use `sphinx_favicon`? 

If I see it correctly, this will be a breaking change because people already using this extension will need to update their conf file after this update, right?

**Comment by 12rambau** [comment]
> If I see it correctly, this will be a breaking change because people already using this extension will need to update their conf file after this update, right?

yes, that's the major issue but there is no real workaround

**Comment by 12rambau** [comment]
I dropped 3.6 tests as it's not a supported version of Python in Github actions

**Review by tcmetzger — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
